sudo: required

env:
- GHCVER=7.6.3
- GHCVER=7.8.4
- GHCVER=7.10.3
- GHCVER=8.0.2
- GHCVER=8.2.1
- GHCVER=head

script:
- curl -sL https://raw.github.com/tomjaguarpaw/neil/master/travis.sh | sh

# To clear the caches go to
#
#     https://travis-ci.org/tomjaguarpaw/haskell-opaleye/caches
#
# (or the equivalent where you run Travis)
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

before_script:
- export POSTGRES_CONNSTRING="user='postgres' dbname='opaleye_test'"
- psql -c 'create database opaleye_test;' -U postgres

addons:
  postgresql: "9.3"
